# Generated by Django 6.0.2 on 2026-02-05 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('atributo_base', models.CharField(choices=[('forca', 'Força'), ('agilidade', 'Agilidade'), ('inteligencia', 'Inteligência'), ('resistencia', 'Resistência'), ('carisma', 'Carisma')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('esforco', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nivel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nome_do_jogador', models.CharField(max_length=100)),
                ('nome_do_heroi', models.CharField(max_length=100)),
                ('classe', models.CharField(choices=[('TIT', 'Titã'), ('VEL', 'Velocista'), ('MEN', 'Mentalista'), ('MUT', 'Mutante')], max_length=3)),
                ('origem', models.CharField(choices=[('HUM', 'Humano Excepcional'), ('EXP', 'Experimento Científico'), ('PSI', 'Psíquico Desperto'), ('CIB', 'Ciborgue'), ('MUT', 'Mutação Natural'), ('COS', 'Energia Cósmica'), ('MIS', 'Entidade Mística'), ('MAL', 'Maldição ou Transformação'), ('CLO', 'Clone ou Criação Artificial'), ('ALI', 'Alienígena')], max_length=3)),
                ('arma', models.CharField(choices=[('SOC', 'Soco / Punho (1d4, crítico 20)'), ('BAS', 'Bastão (1d6, crítico 20)'), ('ADA', 'Adaga (1d6, crítico 18)'), ('ESP', 'Espada (2d8, crítico 19)'), ('MAC', 'Machado (2d10, crítico 20)'), ('MAR', 'Martelo (2d12, crítico 20)'), ('LEN', 'Lâmina de Energia (3d8, crítico 19)'), ('CHI', 'Chicote (1d8, crítico 18)'), ('GAR', 'Garras (2d6, crítico 19)'), ('LAN', 'Lança (2d8, crítico 20)'), ('NUN', 'Nunchaku (2d6, crítico 18)'), ('ARC', 'Arco (1d8, crítico 20)'), ('BES', 'Besta (2d8, crítico 19)'), ('PIS', 'Pistola (2d6, crítico 19)'), ('REV', 'Revólver (2d8, crítico 20)'), ('SUB', 'Submetralhadora (2d6, crítico 18)'), ('RIF', 'Rifle (2d10, crítico 20)'), ('ESC', 'Escopeta (3d8, crítico 20)'), ('SNI', 'Rifle de Precisão (3d10, crítico 20)'), ('CAN', 'Canhão de Energia (4d10, crítico 20)')], max_length=3)),
                ('forca', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('agilidade', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('inteligencia', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('resistencia', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('carisma', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pericias', models.ManyToManyField(blank=True, to='core.pericia')),
            ],
        ),
    ]
