# Generated by Django 6.0.2 on 2026-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pericias',
            field=models.ManyToManyField(blank=True, related_name='personagens', to='core.pericia'),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='atributo_base',
            field=models.CharField(choices=[('FOR', 'Força'), ('AGI', 'Agilidade'), ('INT', 'Inteligência'), ('RES', 'Resistência'), ('CAR', 'Carisma')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
