# Generated by Django 6.0.2 on 2026-02-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_character_pericias_alter_pericia_atributo_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='personagens', to='core.habilidade'),
        ),
    ]
