# Generated by Django 6.0.2 on 2026-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_character_defesa_character_esquiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='defesa',
        ),
        migrations.RemoveField(
            model_name='character',
            name='esquiva',
        ),
        migrations.AlterField(
            model_name='character',
            name='arma',
            field=models.CharField(choices=[('SOC', 'Soco / Punho (1d4, crítico 20)'), ('BAS', 'Bastão (1d6, crítico 20)'), ('ADA', 'Adaga (1d6, crítico 18)'), ('ESP', 'Espada (2d8, crítico 19)'), ('MAC', 'Machado (2d10, crítico 20)'), ('MAR', 'Martelo (2d12, crítico 20)'), ('LEN', 'Lâmina de Energia (3d8, crítico 19)'), ('CHI', 'Chicote (1d8, crítico 18)'), ('GAR', 'Garras (2d6, crítico 19)'), ('LAN', 'Lança (2d8, crítico 20)'), ('NUN', 'Nunchaku (2d6, crítico 18)'), ('ARC', 'Arco (1d8, crítico 20)'), ('BES', 'Besta (2d8, crítico 19)'), ('PIS', 'Pistola (2d6, crítico 19)'), ('REV', 'Revólver (2d8, crítico 20)'), ('SUB', 'Submetralhadora (2d6, crítico 18)'), ('RIF', 'Rifle (2d10, crítico 20)'), ('ESC', 'Escopeta (3d8, crítico 20)'), ('SNI', 'Rifle de Precisão (3d10, crítico 20)'), ('CAN', 'Canhão de Energia (2d10, crítico 20)'), ('RAI', 'Raio laser (3d8, crítico 19)')], max_length=3),
        ),
    ]
