# Generated by Django 6.0.2 on 2026-02-07 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_character_defesa_remove_character_esquiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='defesa_esquiva',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Defesa / Esquiva'),
        ),
        migrations.AlterField(
            model_name='character',
            name='esforco',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='vida',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
