# Generated by Django 6.0.2 on 2026-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_character_defesa_esquiva_alter_character_esforco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='herois/', verbose_name='Foto do Herói'),
        ),
    ]
