# Generated by Django 6.0.2 on 2026-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_character_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='anotacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações do Sistema'),
        ),
    ]
