# Generated by Django 6.0.2 on 2026-02-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_character_anotacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='anotacoes',
        ),
        migrations.AddField(
            model_name='character',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagens', to='core.trilha'),
        ),
    ]
