# Generated by Django 6.0.2 on 2026-02-08 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_character_anotacoes_character_trilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='momentum',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Carga de Momentum'),
        ),
    ]
