# Generated by Django 6.0.2 on 2026-02-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_habilidade_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Índole',
                'verbose_name_plural': 'Índoles',
            },
        ),
        migrations.DeleteModel(
            name='Habilidade_Classe',
        ),
        migrations.AddField(
            model_name='character',
            name='indole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.indole'),
        ),
    ]
