# Generated by Django 6.0.2 on 2026-02-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_indole_delete_habilidade_classe_character_indole'),
    ]

    operations = [
        migrations.AddField(
            model_name='indole',
            name='cor',
            field=models.CharField(default='#00ff88', help_text='Cor em Hexadecimal (ex: #ff4d4d)', max_length=7),
        ),
    ]
